imd/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views


urlpatterns = [

    path('admin/', admin.site.urls, name='admin'),
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),

    path('', include('homepage.urls')),
    path('inventory/', include('imdapp.urls')),
    ]

imdapp/urls.py
from django.conf import settings
from django.urls import path
from . import views
from django.conf.urls.static import static



urlpatterns = [


    path('', views.StockListView.as_view(), name='inventory'),
    path('new', views.StockCreateView.as_view(), name='new-stock'),
    path('stock/<pk>/edit', views.StockUpdateView.as_view(), name='edit-stock'),
    path('stock/<pk>/delete', views.StockDeleteView.as_view(), name='delete-stock'),
    path('stock/<name>', views.StockView.as_view(), name='stockdetails'),
    path('stock/<name>', views.StockView.as_view(), name='stockdetails'),


    path('suppliers/', views.SupplierListView.as_view(), name='suppliers-list'),
    path('suppliers/new', views.SupplierCreateView.as_view(), name='new-supplier'),
    path('suppliers/<pk>/edit', views.SupplierUpdateView.as_view(), name='edit-supplier'),
    path('suppliers/<pk>/delete', views.SupplierDeleteView.as_view(), name='delete-supplier'),
    path('suppliers/<name>', views.SupplierView.as_view(), name='supplier'),

    path('purchases/', views.PurchaseView.as_view(), name='purchases-list'),
    path('purchases/new', views.SelectSupplierView.as_view(), name='select-supplier'),
    path('purchases/new/<pk>', views.PurchaseCreateView.as_view(), name='new-purchase'),
    path('purchases/<pk>/delete', views.PurchaseDeleteView.as_view(), name='delete-purchase'),

    path('sales/', views.SaleView.as_view(), name='sales-list'),
    # path('stockreport/', views.showresult, name='stockreport'),
    path('outwardslip/', views.outwardslip, name='outwardslip'),
    path('inwardslip/', views.inwardslip, name='inwardslip'),

    path('export/', views.export_csv, name='stockre'),
    # path('filterrange/', views.showresult,name='stockreport'),

    path('sales/new', views.SaleCreateView.as_view(), name='new-sale'),
    path('sales/<pk>/delete', views.SaleDeleteView.as_view(), name='delete-sale'),

    path("purchases/<billno>", views.PurchaseBillView.as_view(), name="purchase-bill"),
    path("sales/<billno>", views.SaleBillView.as_view(), name="sale-bill"),

    # path('Master/', views.categorylist, name='category-list'),
    path('Master/new',views.addcategory, name='addcategory'),
    path('Master/subcategory',views.addsubcategory, name='addsubcategory'),
    path('Master/description',views.adddescription, name='adddescription'),



    path('Master/<pk>/edit', views.CategoryUpdateView.as_view(), name='update-category'),
    path('Master/deleteproduct/<int:id>', views.delete_category, name='delete-category'),
    # path('Master/updatecategory/<pk>/edit', views.update_category, name='update-category'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

imdapp/models.py
from django.db import models

# Create your models here.



class Category(models.Model):
    id=models.IntegerField(primary_key=True)
    category=models.CharField(max_length=255)
    subcategory=models.CharField(max_length=255)
    description=models.TextField(max_length=255)
    is_deleted=models.BooleanField(default=False)
    def __str__(self):
        return self.category

    class Meta:
        db_table='Category'

class Subcategory(models.Model):
    id=models.IntegerField(primary_key=True)
    subcategory=models.CharField(max_length=255)
    is_consumable=models.BooleanField(default=False)
    def __str__(self):
        return self.subcategory
    class Meta:
        db_table='Subcategory'


class Description(models.Model):
    id=models.IntegerField(primary_key=True)

    description=models.CharField(max_length=255)
    def __str__(self):
        return self.description

    class Meta:
        db_table='Description'

class Supp(models.Model):
    id=models.IntegerField(primary_key=True)
    name=models.CharField(max_length=255)


    def __str__(self):
        return self.name
    class Meta:
        db_table='Supp'




class Supplier(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.ForeignKey(Supp,on_delete=models.CharField)
    phone = models.CharField(max_length=12, unique=True)
    address = models.TextField()
    email = models.EmailField(max_length=255, unique=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return str(self.name)

class Stock(models.Model):
    STATUS_CHOICE = [
        ('CONSUMABLE', 'CONSUMABLE'),
        ('NON-COMSUMABLE', 'NON-COMSUMABLE'),
    ]
    STATUS_UNIT = [
        ('Mtr', 'Mtr'),
        ('Cm', 'Cm'),
        ('mm', 'mm'),
        ('Kg', 'Kg'),
        ('gm', 'gm'),
        ('Ltr', 'Ltr'),
        ('SqMtr', 'SqMtr'),
        ('SqCm', 'SqCm'),
        ('CuM', 'CuM'),
        ('Ream', 'Ream'),
        ('Doz', 'Doz'),
        ('Pkts', 'Pkts'),
        ('Pairs', 'Pairs'),
        ('Rolls', 'Rolls'),
        ]

    CONDITION = [
        ('GOOD', 'GOOD'),
        ('TORN', 'TORN'),
        ('DAMAGED', 'DAMAGED'),
    ]
    MODE_OF_DELIVERY = [
        ('BY-HAND', 'BY-HAND'),
        ('COURIER', 'COURIER'),
        ('OTHER', 'OTHER'),

    ]
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    subcategory=models.ForeignKey(Subcategory,on_delete=models.CASCADE)
    description=models.ForeignKey(Description,on_delete=models.CASCADE)
    name=models.ForeignKey(Supp,on_delete=models.CASCADE)
    type=models.CharField(max_length=50, choices=STATUS_CHOICE)
    unit=models.CharField(max_length=50,choices=STATUS_UNIT)
    id = models.AutoField(primary_key=True)
    quantity = models.IntegerField(default=1)
    Mode_of_delivery = models.CharField(max_length=50, choices=MODE_OF_DELIVERY)  # received by
    label_code = models.CharField(max_length=20, default="")
    condition = models.CharField(max_length=50, choices=CONDITION)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return str(self.subcategory)






class PurchaseBill(models.Model):
    billno = models.AutoField(primary_key=True)
    time = models.DateTimeField(auto_now=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, related_name='purchasesupplier')

    def __str__(self):
        return "Bill no: " + str(self.billno)

    def get_items_list(self):
        return PurchaseItem.objects.filter(billno=self)

    def get_total_price(self):
        purchaseitems = PurchaseItem.objects.filter(billno=self)
        total = 0
        for item in purchaseitems:
            total += item.totalprice
        return total



class PurchaseBillDetails(models.Model):
    billno = models.ForeignKey(PurchaseBill, on_delete=models.CASCADE, related_name='purchasedetailsbillno')
    total = models.CharField(max_length=50, blank=True, null=True)
    is_deleted=models.BooleanField(default=False)


    def __str__(self):
        return "Bill no: " + str(self.billno.billno)

class PurchaseItem(models.Model):
    billno = models.ForeignKey(PurchaseBill, on_delete=models.CASCADE, related_name='purchasebillno')
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE, related_name='purchaseitem')
    quantity = models.IntegerField(default=1)
    perprice = models.IntegerField(default=1)
    totalprice = models.IntegerField(default=1)
    is_deleted=models.BooleanField(default=False)

    def __str__(self):
        return "Bill no: " + str(self.billno.billno) + ", Item = " + self.stock.subcategory




class SaleBill(models.Model):
    STATUS_CHOICE = [
        ('CONSUMABLE', 'CONSUMABLE'),
        ('NON-COMSUMABLE', 'NON-COMSUMABLE'),
    ]

    CONDITION = [
        ('GOOD', 'GOOD'),
        ('TORN', 'TORN'),
        ('DAMAGED', 'DAMAGED'),
    ]
    MODE_OF_DELIVERY = [
        ('BY-HAND', 'BY-HAND'),
        ('COURIER', 'COURIER'),
        ('OTHER', 'OTHER'),

    ]

    billno = models.AutoField(primary_key=True)
    time = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=150)
    phone = models.CharField(max_length=12)
    address = models.CharField(max_length=200)
    type = models.CharField(max_length=50, choices=STATUS_CHOICE)  # received by
    email = models.EmailField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    description = models.ForeignKey(Description, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    Mode_of_delivery = models.CharField(max_length=50, choices=MODE_OF_DELIVERY)  # received by
    label_code = models.CharField(max_length=20, default="")
    issued_to = models.CharField(max_length=50)
    # condition = models.CharField(max_length=50, choices=CONDITION)
    is_deleted=models.BooleanField(default=False)




    def __str__(self):
        return str(self.name)



    def __str__(self):
        return "Bill no: " + str(self.billno)

    def get_items_list(self):
        return SaleItem.objects.filter(billno=self)

    def get_total_price(self):
        saleitems = SaleItem.objects.filter(billno=self)
        total = 0
        for item in saleitems:
            total += item.totalprice
        return total


# contains the sale stocks made
class SaleItem(models.Model):
    billno = models.ForeignKey(SaleBill, on_delete=models.CASCADE, related_name='salebillno')
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE, related_name='saleitem')
    quantity = models.IntegerField(default=1)
    perprice = models.IntegerField(default=1)
    totalprice = models.IntegerField(default=1)

    # def __str__(self):
    #     return "Bill no: " + str(self.billno.billno) + ", Item = " + self.stock.name
    def __str__(self):
        return "Bill no: " + str(self.billno.billno)

        # return  "Bill no: " + str(self.billno.billno),"Stock Name: " + str(self.stock.subcategory)




# contains the other details in the sales bill
class SaleBillDetails(models.Model):
    billno = models.ForeignKey(SaleBill, on_delete=models.CASCADE, related_name='saledetailsbillno')

    total = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return "Bill no: " + (self.billno.billno)

imdapp/templates/purchases/delete_purchase.html
{% extends "base.html" %}


{% block title %} Delete Purchase {% endblock title %}


{% block content %}
                
    <form method="post">
        
        {% csrf_token %}
        
        <fieldset class="form-group">
            <div style="color:#575757; font-style: bold; font-size: 3rem; border-bottom: 1px solid white;">Delete Purchase Bill</div> <br>
            <h2 style="color:#575757;">Are you sure you want to delete the Purchase Bill No: {{ object.billno }}?</h2>
        </fieldset>

        <div class="form-group">  
            <button type="submit" class="btn btn-danger">Yes, Delete</button>
            <a href="{% url 'purchases-list' %}" class="btn btn-secondary">Cancel</a>
        </div>
        
    </form>

{% endblock content %}

imdapp/templates/purchases/inwardslip.html
{% extends "base.html" %}

{% load widget_tweaks %}


{% block title %} Inward Slip List {% endblock title %}



{% block content %}
<div class="card text-left">
      <div class="card-header" style="background-color:#01345B">
        <div class="row" style="color: white; font-style: bold; font-size: 3.5rem">
        <div class="col-md-8" style="font-family: 'Alkalami'" >Inwards Slip</div>
        </div>
      </div>
</div>

<!--    <div class="row" style="color: #575757; font-style: bold; font-size: 3rem;">-->
<!--        <div class="col-md-8">Inword Slip</div>-->
<!--        <div class="col-md-4">-->
<!--            <div style="float:right;"> <a class="btn btn-success" href="{% url 'new-sale' %}">New Outgoing Stock</a> </div>-->
<!--        </div>-->
<!--    </div>-->

<br>
<div class="form-group">
    <input id="myInput" type="text" class="search form-control"  placeholder="Search">
</div>

<form  action="{% url 'inwardslip' %}" method="POST">
        {% csrf_token %}
    <div>
        From: <input type="date" name="fromdate">
        To: <input type="date" name="todate">
        <input class="btn btn-secondary" type="submit" value="Search">


    </div>
</form>



 <table class="table table-css table-bordered table-hover" id="myTable" onkeyup="myFunction()">

        <thead class="thead-dark align-middle">
            <tr><!-- Log on to codeastro.com for more projects -->
                <th width="5%">Bill No.</th>
                <th width="15%">Date</th>
                <th width="10%">From Whom Received</th>
                <th width="15%">Description Of Stores</th>
                <th width="10%">Quantity</th>
                <th width="15%">Recd. By</th>
                <th width="15%">Conditions</th>
                <th width="30%">Actions</th>
            </tr>
        </thead>

{% if bills %}

        <tbody>
            {% for purchase in bills %}
            <tr>
                <td class="align-middle"> <p>{{ purchase.billno }}</p> </td>
                <td class="align-middle">{{ purchase.time.date }}</td>
                <td class="align-middle">{% for item in purchase.get_items_list %} {{ item.stock.name }} <br> {% endfor %}</td>
                <td class="align-middle">{% for item in purchase.get_items_list %} {{ item.stock.description }} <br> {% endfor %}</td>
                <td class="align-middle">{% for item in purchase.get_items_list %} {{ item.stock.quantity }} <br> {% endfor %}</td>
                <td class="align-middle">{% for item in purchase.get_items_list %} {{ item.stock.Mode_of_delivery }} <br> {% endfor %}</td>
                <td class="align-middle">{% for item in purchase.get_items_list %} {{ item.stock.condition}} <br> {% endfor %}</td>
                <td class="align-middle"> <a href="{% url 'purchase-bill' purchase.billno %}" class="btn btn-secondary btn-sm">View</a></td>
<!--                    <a href="{% url 'delete-purchase' purchase.pk %}" class="btn btn-danger btn-sm">Delete</a> -->
            </tr>
            {% endfor %}
        </tbody>
    </table>

<div >
            <a href="{% url 'stockre' %}" class="btn btn-secondary">Export CSV</a>

</div>




    <div class="align-middle"><!-- Log on to codeastro.com for more projects -->
        {% if is_paginated %}

            {% if page_obj.has_previous %}
                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}

        {% endif %}
    </div>

{% else %}

        <tbody></tbody>  <!-- Log on to codeastro.com for more projects -->
    </table>

    <br><br><br><br><br><br><br><br>
    <div style="color: #575757; font-style: bold; font-size: 1.5rem; text-align: center;">The records are empty. Please try adding some.</div>

{% endif %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>

{% endblock content %}

imdapp/templates/purchases/new_purchase.html
{% extends "base.html" %}
{% load static %}


{% block title %} New Purchase {% endblock title %}


{% block content %}
  <div class="card text-left">
      <div class="card-header" style="background-color:#01345B">
        <div class="row" style="color: white; font-style: bold; font-size: 3.5rem">
        <div class="col-md-8" style="font-family: 'Alkalami'" >Inward Items</div>
        <div class="col-md-4">
            <div style="float:right; margin-top:8%">
                <button type="button" class="btn btn-danger" href="{% url 'new-supplier' %}">New Supplier</button> </div>
        </div>
    </div>
      </div>
      <div class="card-body" style="font-family: 'Alkalami'">

<!--    <div style="color:#575757; font-style: bold; font-size: 3rem; border-bottom: 1px solid white;">New Purchase</div>-->

        <br><!-- Log on to codeastro.com for more projects -->

        <div class="panel panel-default">
            <div class="panel-heading panel-heading-text">Supplier Details</div>
            <div class="panel-body">

                <div class="form-group">
                    <label for="id_name" class="panel-body-text">Supplier Name:</label>
                    <input type="text" class="form-control textinput" id="id_name" value="{{ supplier.name }}" disabled>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="id_phone" class="panel-body-text">Phone No:</label>
                        <input type="text" class="form-control textinput" id="id_phone" value="{{ supplier.phone }}" disabled>
                    </div>
<!--                    <div class="form-group col-md-6">-->
<!--                        <label for="id_gstin" class="panel-body-text">GSTIN No:</label>-->
<!--                        <input type="gstin" class="form-control textinput" id="id_gstin" value="{{ supplier.gstin }}" disabled>-->
<!--                    </div>-->
                </div>

            </div><!-- Log on to codeastro.com for more projects -->
        </div>

        <br>

        <form method="post" class="panel panel-default">

            {% csrf_token %}
            {{ formset.management_form }}

            <div class="panel-heading panel-heading-text">Product Details</div>

                <div id="stockitem">
                    <div class="panel-body">
                    {% for form in formset %}
                        <div class="row form-row">
                            <div class="form-group col-md-6">
                                {{ form.stock.errors }}
                                <label class="panel-body-text">Stock:</label>
                                {{ form.stock }}
                            </div><!-- Log on to codeastro.com for more projects -->
                            <div class="form-group col-md-2">
                                <label class="panel-body-text">Price per item:</label>
                                {{ form.perprice }}
                            </div>
                            <div class="form-group col-md-2">
                                {{ form.quantity.errors }}
                                <label class="panel-body-text">Quantity:</label>
                                {{ form.quantity }}
                            </div><!-- Log on to codeastro.com for more projects -->
                            <div class="form-group col-md-1">
                                <label class="panel-body-text">Price:</label>
                                <input type="text" class="textinput form-control totalprice" value="1" disabled required>
                            </div>
                            <div class="form-group col-md-1">
                                <label class="panel-body-text" style="color: #000">.</label>
                                <button class="form-control btn btn-danger remove-form-row">-</button>
                            </div>
                        </div>
                    {% endfor %}
                        <div style="text-align: right;">
                            <a href="#" class="add-form-row">+ Add More</a>
                        </div>
                    </div>
                </div>


            <br><!-- Log on to codeastro.com for more projects -->

            <div class="align-middle">
                <button type="submit" class="btn btn-info">Add to Purchases</button>
                <a href="{% url 'select-supplier' %}" class="btn btn-danger">Go Back</a>
                <a href="{% url 'purchases-list' %}" class="btn btn-secondary">Cancel</a>
            </div>

        </form>

    </div>

    <!-- Custom JS to add and remove item forms --><!-- Log on to codeastro.com for more projects -->
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dialogbox.js' %}"></script>
    <script type="text/javascript">

        //creates custom alert object
        var custom_alert = new custom_alert();

        function updateElementIndex(el, prefix, ndx) {
            var id_regex = new RegExp('(' + prefix + '-\\d+)');
            var replacement = prefix + '-' + ndx;
            if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
            if (el.id) el.id = el.id.replace(id_regex, replacement);
            if (el.name) el.name = el.name.replace(id_regex, replacement);
        }

        //stores the total no of item forms
        var total = 1;

        function cloneMore(selector, prefix) {
            var newElement = $(selector).clone(true);
            //var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
            newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function() {
                var name = $(this).attr('name')
                if(name) {
                    name = name.replace('-' + (total-1) + '-', '-' + total + '-');
                    var id = 'id_' + name;
                    $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
                }
            });
            newElement.find('label').each(function() {
                var forValue = $(this).attr('for');
                if (forValue) {
                forValue = forValue.replace('-' + (total-1) + '-', '-' + total + '-');
                $(this).attr({'for': forValue});
                }
            });
            total++;
            $('#id_' + prefix + '-TOTAL_FORMS').val(total);
            $(selector).after(newElement);
            return false;
        }

        function deleteForm(prefix, btn) {
            //var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
            if (total > 1){
                btn.closest('.form-row').remove();
                var forms = $('.form-row');
                $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
                for (var i=0, formCount=forms.length; i<formCount; i++) {
                    $(forms.get(i)).find(':input').each(function() {
                        updateElementIndex(this, prefix, i);
                    });
                }
                total--;
            } else {
                custom_alert.render("Field cannot be deleted");
            }
            return false;
        }

        $(document).on('click', '.add-form-row', function(e){
            e.preventDefault();
            cloneMore('.form-row:last', 'form');
            return false;
        });

        $(document).on('click', '.remove-form-row', function(e){
            e.preventDefault();
            deleteForm('form', $(this));
            return false;
        });


        //updates the total price by multiplying 'price per item' and 'quantity'
        $(document).on('change', '.setprice', function(e){
            e.preventDefault();
            //gets the values
            var element = $(this);
            var quantity = element.parents('.form-row').find('.quantity').val();
            var perprice = element.parents('.form-row').find('.price').val();
            //calculates the total
            var tprice = quantity * perprice;
            //sets it to field
            element.parents('.form-row').find('.totalprice').val(tprice);
            return false;
        });

    </script>

{% endblock content %}

imdapp/templates/purchases/purchases_list.html
{% extends "base.html" %}

{% load widget_tweaks %}


{% block title %} Purchases List {% endblock title %}


{% block content %}
    <div class="card text-left">
          <div class="card-header" style="background-color:#01345B">
            <div class="row" style="color: white; font-style: bold; font-size: 3.5rem">
            <div class="col-md-8" style="font-family: 'Alkalami'" >Inward List</div>
            <div class="col-md-4">
                <div style="float:right; margin-top:8%"> <a class="btn btn-danger" href="{% url 'new-stock' %}">Add New Stock</a> </div>
            </div>
            </div>
          </div>
    </div>
    <div class="row" style="color: #575757; font-style: bold; font-size: 3rem;">
        <div class="col-md-8">Purchases List</div>
        <div class="col-md-4">            <!-- Log on to codeastro.com for more projects -->   
            <div style="float:right;"> <a class="btn btn-success" href="{% url 'select-supplier' %}">New Incoming Stock</a> </div>
        </div>
    </div>

    <br>

    <table class="table table-css table-hover table-bordered">

        <thead class="thead-dark align-middle">
            <tr>
                <th width="10%">Bill No.</th>
                <th width="10%">Date</th>
                <th width="10%">From Whom Received</th>
                <th width="15%">Descriptions</th>
                <th width="10%">Quantity Purchased</th>
                <th width="10%">Recd. By </th>
                <th width="15%">Total Purchased Price</th>
                <th width="10%">Condition</th>
                <th width="25%">Actions</th>
            </tr>
        </thead>

{% if bills %}

        <tbody>         
            {% for purchase in bills %}
            <tr>
                <td class="align-middle"> <p>{{ purchase.billno }}</p> </td>
                <td class="align-middle">{{ purchase.time.date }}</td>
                <td class="align-middle">{% for item in purchase.get_items_list %} {{ item.stock.name }} <br> {% endfor %}</td>
<!--                <td class=""> -->
<!--                    {% if purchase.supplier.is_deleted %}-->
<!--                        {{ purchase.supplier }}<br> -->
<!--                    {% else %}-->
<!--                        <a href="{% url 'supplier' purchase.supplier.name %}">{{ purchase.supplier }}</a> <br> -->
<!--                    {% endif %}-->
<!--                    <small style="color: #909494">Ph No : {{ purchase.supplier.phone }}</small> -->
<!--                </td>&lt;!&ndash; Log on to codeastro.com for more projects &ndash;&gt;-->
                <td class="align-middle">{% for item in purchase.get_items_list %} {{ item.stock.description }} <br> {% endfor %}</td>
                <td class="align-middle">{% for item in purchase.get_items_list %} {{ item.stock.quantity }} <br> {% endfor %}</td>
                <td class="align-middle">{% for item in purchase.get_items_list %} {{ item.stock.Mode_of_delivery }} <br> {% endfor %}</td>
                <td class="align-middle">${{ purchase.get_total_price }}</td>
                <td class="align-middle">{% for item in purchase.get_items_list %} {{ item.stock.condition}} <br> {% endfor %}</td>
                <td class="align-middle"> <a href="{% url 'purchase-bill' purchase.billno %}" class="btn btn-secondary btn-sm">View</a> <a href="{% url 'delete-purchase' purchase.pk %}" class="btn btn-danger btn-sm">Delete</a> </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>

    <div class="align-middle">
        {% if is_paginated %}

            {% if page_obj.has_previous %}
                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}

        {% endif %}
    </div>

{% else %}

        <tbody></tbody>  <!-- Log on to codeastro.com for more projects --> 
    </table>

    <br><br><br><br><br><br><br><br>
    <div style="color: #575757; font-style: bold; font-size: 1.5rem; text-align: center;">The records are empty. Please try adding some.</div>
<!-- Log on to codeastro.com for more projects -->
{% endif %}

{% endblock content %}

imdapp/templates/purchases/select_supplier.html
{% extends "base.html" %}


{% block title %} New Purchase {% endblock title %}


{% block content %}

    <div class="card text-left">
      <div class="card-header" style="background-color:#01345B">
        <div class="row" style="color: white; font-style: bold; font-size: 3.5rem">
        <div class="col-md-8" style="font-family: 'Alkalami'" >New Purchase</div>
             <div class="col-md-4">
                 <div style="float:right; margin-top:8%"></div>
        </div>
      </div>
    </div>

    <br>

    <form method="post">

        {% csrf_token %}
        {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}

        <br>
        <div class="align-middle">
            <button type="submit" class="btn btn-success">Next</button>
            <a href="{% url 'purchases-list' %}" class="btn btn-secondary">Cancel</a>
        </div>

    </form>

{% endblock content %}